substitutions:
  name: presenza-camera
  friendly_name: "Presenza Camera"

packages:
  # Usa il TUO fork con TSL2561
  presence_lite: github://pla10/my-presence-lite-tsl2561/everything-presence-lite-ha-no-ble.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: C6Ee/UhXL7EPmSrySxKO4rDyE4Q4XwpMvbrjc3eo/LY=

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.52
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 192.168.0.1
